name: dyslexaid
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mlkit_text_recognition: ^0.16.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  provider: ^6.1.1
  sensors_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/opendyslexic-0.92/OpenDyslexic-Regular.otf
        - asset: assets/fonts/opendyslexic-0.92/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/opendyslexic-0.92/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/opendyslexic-0.92/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-VariableFont_wght.ttf
